version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: swapmind_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=swapmind
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: swapmind_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: swapmind
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:

